
spring:
  kafka:
    bootstrap-servers: pkc-l7pr2.ap-south-1.aws.confluent.cloud:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: weekly-sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: net.engineeringdigest.journalApp.model
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="X" password="X";
      session:
        timeout:
          ms: 45000
  redis:
    host : redis-10478.crce263.ap-south-1-1.ec2.cloud.redislabs.com
    port: 10478
    username: default
    password: DZIXXJeEegIew3J6estIhIUDk58VOtCZ
    ssl: true
  data:
    mongodb:
      uri: mongodb+srv://AbhayRaj011:(SatyamRaj011)@journalappcluster.5qo1ask.mongodb.net/?
      database: journaldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: abhayraj620285@gmail.com
    password: feftcdvvyqbtwsmb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

weather:
  api:
    key: 9d9c3545793f3ad060568245a64334c5


